### ISSUE TITLE
gettext ext is required

### ISSUE THREAD

**Issue by PHPGangsta** [halon/sp-enduser#21]
In the README.md it says the "gettext" extension is recommented. It's definitly required. Without gettext I get this error:

> Dec  8 19:14:25 halonenduser php: PHP Fatal error:  Uncaught  --> Smarty Compiler: Syntax error in template "file:/var/www/html/templates/header.tpl"  on line 9 "<title>{$title|gettext|escape} | {$pagename|escape}</title>" unknown modifier "gettext" <--
> Dec  8 19:14:25 halonenduser php:   thrown in /var/www/html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php on line 9

I added some more extensions to composer.json, please see PR #20

**Comment by Harrens** [comment]
https://github.com/halon/sp-enduser/commit/21ce75c91f544a9a4bd478660c654475136b00cc

Documentation updated.
